version: '3'

services:
  control-server:
    container_name: control-server
    restart: always
    image: "server:latest"
    ports:
      - "5000:5000"

  control-joystick:
    container_name: control-joystick
    restart: always
    privileged: true
    image: "joystick:latest"
    ports:
     - "5001:5000"
    environment:
      #- LOGGING=CRITICAL
      - ENV_SOCKETIOSERVER=control-server
    volumes:
      - /dev:/dev:ro

#volumes:
#  nginx:
#  prometheus:
#  dist:

