version: '3'

services:
  socket-server:
    container_name: socket-server
    restart: always
    image: "cmb87/smart-cam-server:latest-arm32v7"
    ports:
      - "5000:5000"
    environment:
      - LOGGING=INFO

  socket-cam-simple:
    container_name: socket-cam-simple
    restart: always
    privileged: true
    image: "cmb87/smart-cam-client:simple-latest-arm32v7"
    ports:
     - "5001:5001"
    environment:
      - LOGGING=INFO
      - SERVERHOSTNAME=socket-server
      - VIDEODEVICE=0
    devices:
      - /dev/video0 #:/dev/video0

#volumes:
#  nginx:
#  prometheus:
#  dist:

